version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: catalogue
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 100M
      restart_policy:
        condition: on-failure
    ports:
      - "4000:3000"
    networks:
      - webnet
networks:
  webnet:
